version: '3'

services:
  postgres-slave:
    container_name: slave
    image: postgres:13.10
    user: postgres
    environment:
      POSTGRES_DB: application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - /var/www/pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: >
      bash -c "while true; do sleep 1; done"
