---
- name: Configure replica
  hosts: slave
  become: yes
  gather_facts: yes
  vars:
    application_path: "/var/www"
    master_host: "192.168.1.71"

  tasks:
    - name: Create Docker Compose directory
      file:
        path: "{{ application_path }}"
        state: directory
        mode: '0755'

    - name: Copy docker-compose
      copy:
        src: ./files/docker-compose.slave.yml
        dest: "{{ application_path }}/docker-compose.yml"
        mode: "0644"
    
    - name: Copy .pgpass
      copy:
        src: ./files/configs/.pgpass
        dest: "{{ application_path }}/.pgpass"
        mode: "0600"

    - name: Copy postgresql.auto.conf
      copy:
        src: ./files/configs/postgresql.auto.conf
        dest: "{{ application_path }}/postgresql.auto.conf"
        mode: "0644"

    - name: Copy env
      copy:
        src: ./files/.env
        dest: "{{ application_path }}/.env"
        mode: "0644"

    - name: Up containers
      community.docker.docker_compose_v2:
        project_src: "{{ application_path }}"
        state: present

    - name: Copy a .pgpass into the container
      community.docker.docker_container_copy_into:
        container: slave
        path: /var/www/.pgpass
        container_path: /var/lib/postgresql/.pgpass

    - name: Chmod && Chown postgresql/data
      ansible.builtin.file:
        path: /var/www/pg-data
        state: directory
        owner: "999"
        group: "999"
        mode: '0750'
        recurse: yes

    - name: Make backup
      community.docker.docker_container_exec:
        user: "postgres"
        container: slave
        command: "pg_basebackup -h {{ master_host }} -U repl_user -D /var/lib/postgresql/data -R -X stream -w -C -S pg_slot_repl"

    - name: Copy a postgresql.auto.conf into the container
      community.docker.docker_container_copy_into:
        container: slave
        path: /var/www/postgresql.auto.conf
        container_path: /var/lib/postgresql/data/postgresql.auto.conf
    
    - name: Start pg
      community.docker.docker_container_exec:
        container: slave
        command: "pg_ctl start -D /var/lib/postgresql/data"
        user: "postgres"
