---
- name: Monitoring
  hosts: slave
  become: yes
  gather_facts: yes
  vars:
    master_host: "{{ hostvars['backend']['ansible_host'] }}"
    replica_host: "{{ hostvars['replica']['ansible_host'] }}"
    monitoring_network: "monitoring"
    application_path: "/var/www"
    grafana_url: "http://localhost:3000"

  tasks:
    - name: Create network
      community.docker.docker_network:
        name: "{{ monitoring_network }}"
        driver: bridge
        state: present

    - name: Up exporter container for master
      community.docker.docker_container:
        name: exporter-master
        image: "quay.io/prometheuscommunity/postgres-exporter"
        networks:
          - name: "{{ monitoring_network }}"
            aliases:
              - exporter-master
        env:
          DATA_SOURCE_URI: "{{ master_host }}:5432/kittygram?sslmode=disable"
          DATA_SOURCE_USER: "postgres"
          DATA_SOURCE_PASS: "secret"

    - name: Up exporter container for slave
      community.docker.docker_container:
        name: exporter-slave
        image: "quay.io/prometheuscommunity/postgres-exporter"
        networks:
          - name: "{{ monitoring_network }}"
            aliases:
              - exporter-slave
        env:
          DATA_SOURCE_URI: "{{ replica_host }}:5432/kittygram?sslmode=disable"
          DATA_SOURCE_USER: "postgres"
          DATA_SOURCE_PASS: "secret"

    - name: Copy prometheus.yml
      copy:
        src: ./files/configs/prometheus.yml
        dest: "{{ application_path }}/prometheus.yml"
        mode: "0644"

    - name: Up prometheus
      community.docker.docker_container:
        name: prometheus
        image: "prom/prometheus"
        networks:
          - name: "{{ monitoring_network }}"
            aliases:
              - prometheus
        volumes:
          - "{{ application_path }}/prometheus.yml:/etc/prometheus/prometheus.yml"
        ports:
          - "9090:9090"

    - name: Create volume for grafana
      community.docker.docker_volume:
        name: grafana-storage

    - name: Up grafana
      community.docker.docker_container:
        name: grafana
        image: "grafana/grafana-enterprise"
        networks:
          - name: "{{ monitoring_network }}"
            aliases:
              - grafana
        volumes:
          - "grafana-storage:/var/lib/grafana"
        ports:
          - "3000:3000"

    - name: Wait for Prometheus to start
      ansible.builtin.wait_for:
        port: 9090
        host: "localhost"
        delay: 10
        timeout: 60

    - name: Wait for Grafana to start
      ansible.builtin.wait_for:
        port: 3000
        host: "localhost"
        delay: 10
        timeout: 60

    - name: create prometheus datasource
      community.grafana.grafana_datasource:
        name: prometheus
        ds_type: prometheus
        url: "{{ grafana_url }}"
        ds_url: "http://prometheus:9090"
        access: proxy
        tls_skip_verify: true
        uid: "pg-prometheus"

    - name: Copy dashboard
      copy:
        src: ./files/configs/db_dash.json
        dest: "/var/www/db_dash.json"
        mode: "0644"

    - name: Export dashboard
      community.grafana.grafana_dashboard:
        url: "{{ grafana_url }}"
        path: "/var/www/db_dash.json"
