---
- name: Run application
  hosts: app
  become: yes
  gather_facts: yes
  vars:
    application_path: "/var/www"
    venv_path: "/opt/myvenv"

  tasks:
    - name: "Set ansible_python_interpreter"
      ansible.builtin.set_fact:
        ansible_python_interpreter: "{{ venv_path }}/bin/python"

    - name: Create Docker Compose directory
      file:
        path: "{{ application_path }}"
        state: directory
        mode: '0755'

    - name: Copy docker-compose
      copy:
        src: ./files/docker-compose.production.yml
        dest: "{{ application_path }}/docker-compose.yml"
        mode: "0644"
      
    - name: Copy pg_hba.conf
      copy:
        src: ./files/configs/pg_hba.conf
        dest: "{{ application_path }}/pg_hba.conf"
        mode: "0644"
      
    - name: Copy postgresql.conf
      copy:
        src: ./files/configs/postgresql.conf
        dest: "{{ application_path }}/postgresql.conf"
        mode: "0644"

    - name: Copy env
      copy:
        src: ./files/.env
        dest: "{{ application_path }}/.env"
        mode: "0644"
    
    - name: Docker compose up
      community.docker.docker_compose_v2:
        project_src: "{{ application_path }}"
        state: present
    
    - name: Copy a pg_hba.conf into the container
      community.docker.docker_container_copy_into:
        container: postgres
        path: /var/www/pg_hba.conf
        container_path: /var/lib/postgresql/data/pg_hba.conf
        owner_id: "999"
        group_id: "999"
    
    - name: Copy a postgresql.conf into the container
      community.docker.docker_container_copy_into:
        container: postgres
        path: /var/www/postgresql.conf
        container_path: /var/lib/postgresql/data/postgresql.conf
        owner_id: "999"
        group_id: "999"

    - name: Re-start postgres
      community.docker.docker_container:
        name: postgres
        state: started
        restart: yes

    - name: Wait for PostgreSQL to start
      ansible.builtin.wait_for:
        port: 5432
        host: "localhost"
        delay: 5
        timeout: 60

    - name: Make migration
      community.docker.docker_container_exec:
        container: backend
        command: "python3 manage.py migrate"
        detach: false

    - name: "Выполнить запрос к pg_roles"
      community.postgresql.postgresql_query:
        query: |
          SELECT EXISTS(
            SELECT 1 FROM pg_roles WHERE rolname = 'repl_user'
          ) AS role_exists;
        db: "kittygram"
        login_host: "localhost"
        login_user: "postgres"
        login_password: "secret"
      register: pg_role_check

    - name: Create role for replication
      community.postgresql.postgresql_query:
        db: "kittygram"
        login_host: "localhost"
        login_user: "postgres"
        login_password: "secret"
        query: "CREATE ROLE repl_user WITH REPLICATION LOGIN PASSWORD 'secret';"
      when: not pg_role_check.query_result[0].role_exists
